export class OnstepX {
    firmwareVersion = '1.0';
    localDateTime = Date();
    utcOffset = 0;
    siteLongitude = 0;
    siteLatitude = 0;
    siteElevation = 0;
    isAtHome = false;
    isHoming =false;
    isParked = false;
    isParking = false;
    isSlewing = false;
    isGuiding = false;
    isTracking = false;
    autoHomeAtStartup = false;
    raHomeOffset = 0;                   // 
    decHomeOffset = 0;                  // 
    currentRA = 0;                  // 0-24 hr
    currentDec = 0;                 // -90 to +90  deg
    currentAlt = 0;                 // -90 to +90 deg
    currentAz = 0;                  // 0-360 deg
    targetRA = 0;                   // 0-24 hr
    targetDec = 0;                  // -90 to +90 deg
    maxSlewSpeed = 4;               // Degrees per second
    gotoRate = 'Normal'             // VerySlow, Slow, Normal, Fast or VeryFast
    gotoAlert = false;                 // Audible alert when goto complete
    flipAuto = false;                  // Auto meridian flip when limit reached
    flipPauseHome = false;             // Pause at Home during meridian flip
    flipPierSide = 'East'               // East, West or Both
    pulseGuideRate = 1;             // 0.25, 0.5 or 1 (x sidereal rate)
    guideRate = 'Fast'                  // 2x, 4x, 8x, 20x, 48x, Fast or VeryFast
    trackingRate = 'Sidereal'               // Sidereal, Lunar, Solar or King
    trackingCompensation = 'Off'       // Full, RefractionOnly or Off
    trackingDualAxis = false;
    backlashRa = 0;                 // 0-3600 arcsec
    backlashDec = 0;                // 0-3600 arcsec
    limitHorizon = -10;               // -30 to +30 deg
    limitOverhead = 90;              // 60-90 deg
    limitMeridianEast = 0;          // -270 to +270 deg
    limitMeridianWest = 0;          // -270 to +270 deg    
};